name:                yesodFromScratch
version:             0.1.0.0
github:              "githubuser/yesodFromScratch"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yesodFromScratch#readme>

dependencies:
  - base
  - yesod 
  - yesod-core 
  - yesod-auth 
  - yesod-static 
  - yesod-form 
  - classy-prelude 
  - classy-prelude-conduit 
  - classy-prelude-yesod 
  - bytestring 
  - text 
  - persistent 
  - persistent-postgresql 
  - persistent-template 
  - template-haskell
  - monad-control 
  - wai-extra 
  - yaml 
  - http-client-tls 
  - http-conduit 
  - directory 
  - warp 
  - data-default
  - aeson 
  - aeson-casing
  - conduit 
  - monad-logger 
  - fast-logger 
  - wai-logger 
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - foreign-store
  - esqueleto
  - fakedata
  - random
  - aeson-qq
  - transformers
  - mtl
  - monad-validate
  - validation
  - lens
  - wai-cors
  - uuid
  - aeson-typescript
  - cookie
  - time
library:
  source-dirs: src

executables:
  yesodFromScratch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesodFromScratch

tests:
  yesodFromScratch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesodFromScratch
